#if !canImport(ObjectiveC)
import XCTest

extension AssertionConcernErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionConcernErrorTests = [
        ("testDebugDescriptionIsNotEmpty", testDebugDescriptionIsNotEmpty),
        ("testDebugDescriptionIsNotStatic", testDebugDescriptionIsNotStatic),
        ("testDescriptionIsNotEmpty", testDescriptionIsNotEmpty),
        ("testDescriptionIsNotStatic", testDescriptionIsNotStatic),
    ]
}

extension AssertionConcernGroupSatsifyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionConcernGroupSatsifyTests = [
        ("testErrorContent", testErrorContent),
        ("testErrorType", testErrorType),
        ("testWithEmptyGroups", testWithEmptyGroups),
    ]
}

extension AssertionConcernSatisfyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionConcernSatisfyTests = [
        ("testErrorContent", testErrorContent),
        ("testErrorType", testErrorType),
        ("testWithNilArguments", testWithNilArguments),
    ]
}

extension AssertionGroupAllTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionGroupAllTests = [
        ("testAssignValue", testAssignValue),
        ("testEmptyBlock", testEmptyBlock),
        ("testExecuteResultIfFailed", testExecuteResultIfFailed),
        ("testWithValidAssertions", testWithValidAssertions),
    ]
}

extension AssertionGroupAnyOfTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionGroupAnyOfTests = [
        ("testAnyCondition", testAnyCondition),
        ("testAssignValue", testAssignValue),
        ("testEmptyBlock", testEmptyBlock),
        ("testExecuteBeforeFirstSuccessful", testExecuteBeforeFirstSuccessful),
        ("testExecuteResultIfAllIsFailed", testExecuteResultIfAllIsFailed),
        ("testWithValidAssertions", testWithValidAssertions),
    ]
}

extension AssertionGroupLazyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionGroupLazyTests = [
        ("testAssignValue", testAssignValue),
        ("testEmptyBlock", testEmptyBlock),
        ("testExecuteBeforeFirstFail", testExecuteBeforeFirstFail),
        ("testExecuteResultIfFailed", testExecuteResultIfFailed),
        ("testWithValidAssertions", testWithValidAssertions),
    ]
}

extension AssertionNotificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionNotificationTests = [
        ("testCreateMethod", testCreateMethod),
        ("testCreateMethodWithEmptyData", testCreateMethodWithEmptyData),
        ("testCustomDebugStringConvertible", testCustomDebugStringConvertible),
        ("testCustomStringConvertible", testCustomStringConvertible),
        ("testEquatableWithDifferentFile", testEquatableWithDifferentFile),
        ("testEquatableWithDifferentLine", testEquatableWithDifferentLine),
        ("testEquatableWithDifferentMessage", testEquatableWithDifferentMessage),
        ("testEquatableWithSameData", testEquatableWithSameData),
    ]
}

extension BetweenBoundsComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenBoundsComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenBoundsDifferentBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenBoundsDifferentBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenBoundsSameBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenBoundsSameBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenClosedRangeComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenClosedRangeComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenMinMaxComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenMinMaxComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenMinMaxDifferentBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenMinMaxDifferentBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenMinMaxSameBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenMinMaxSameBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenPartialRangeFromComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenPartialRangeFromComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BetweenPartialRangeThroughComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenPartialRangeThroughComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
    ]
}

extension BetweenRangeComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenRangeComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testInRange", testInRange),
        ("testMaximumEqual", testMaximumEqual),
        ("testMinimumEqual", testMinimumEqual),
        ("testOutOfRangeMaximum", testOutOfRangeMaximum),
        ("testOutOfRangeMinimum", testOutOfRangeMinimum),
    ]
}

extension BoolAssertionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoolAssertionsTests = [
        ("testIsFalseCustomMessage", testIsFalseCustomMessage),
        ("testIsFalseDefaultMessage", testIsFalseDefaultMessage),
        ("testIsFalseNotValidCase", testIsFalseNotValidCase),
        ("testIsFalseValidCase", testIsFalseValidCase),
        ("testIsTrueCustomMessage", testIsTrueCustomMessage),
        ("testIsTrueDefaultMessage", testIsTrueDefaultMessage),
        ("testIsTrueNotValidCase", testIsTrueNotValidCase),
        ("testIsTrueValidCase", testIsTrueValidCase),
    ]
}

extension ClassAssertionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClassAssertionsTests = [
        ("testIsNotSameInstanceAsCustomMessage", testIsNotSameInstanceAsCustomMessage),
        ("testIsNotSameInstanceAsDefaultMessage", testIsNotSameInstanceAsDefaultMessage),
        ("testIsNotSameInstanceAsNotValidCase", testIsNotSameInstanceAsNotValidCase),
        ("testIsNotSameInstanceAsValidCase", testIsNotSameInstanceAsValidCase),
        ("testIsSameInstanceAsCustomMessage", testIsSameInstanceAsCustomMessage),
        ("testIsSameInstanceAsDefaultMessage", testIsSameInstanceAsDefaultMessage),
        ("testIsSameInstanceAsNotValidCase", testIsSameInstanceAsNotValidCase),
        ("testIsSameInstanceAsValidCase", testIsSameInstanceAsValidCase),
    ]
}

extension ContainedInSequenceTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContainedInSequenceTypesTests = [
        ("testContainedInCustomMessage", testContainedInCustomMessage),
        ("testContainedInDefaultMessage", testContainedInDefaultMessage),
        ("testContainedInEmptyArray", testContainedInEmptyArray),
        ("testContainedInNotValidCase", testContainedInNotValidCase),
        ("testContainedInSampleArray", testContainedInSampleArray),
        ("testNotContainedInCustomMessage", testNotContainedInCustomMessage),
        ("testNotContainedInDefaultMessage", testNotContainedInDefaultMessage),
        ("testNotContainedInEmptyArray", testNotContainedInEmptyArray),
        ("testNotContainedInNotValidCase", testNotContainedInNotValidCase),
        ("testNotContainedInSampleArray", testNotContainedInSampleArray),
    ]
}

extension EquatableAssertionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EquatableAssertionsTests = [
        ("testIsEqualToCustomMessage", testIsEqualToCustomMessage),
        ("testIsEqualToDefaultMessage", testIsEqualToDefaultMessage),
        ("testIsEqualToNotValidCase", testIsEqualToNotValidCase),
        ("testIsEqualToValidCase", testIsEqualToValidCase),
        ("testIsNotEqualToCustomMessage", testIsNotEqualToCustomMessage),
        ("testIsNotEqualToDefaultMessage", testIsNotEqualToDefaultMessage),
        ("testIsNotEqualToNotValidCase", testIsNotEqualToNotValidCase),
        ("testIsNotEqualToValidCase", testIsNotEqualToValidCase),
    ]
}

extension GreaterOrEqualComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterOrEqualComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension GreaterOrEqualDifferentBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterOrEqualDifferentBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension GreaterOrEqualSameBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterOrEqualSameBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension GreaterThanComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterThanComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension GreaterThanDifferentBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterThanDifferentBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension GreaterThanSameBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterThanSameBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension HasSizeCollectionTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HasSizeCollectionTypesTests = [
        ("testHasSizeCustomMessage", testHasSizeCustomMessage),
        ("testHasSizeDefaultMessage", testHasSizeDefaultMessage),
        ("testHasSizeEmptyArray", testHasSizeEmptyArray),
        ("testHasSizeNotValidCase", testHasSizeNotValidCase),
        ("testHasSizeSampleArray", testHasSizeSampleArray),
    ]
}

extension IsBlankBinaryFloatingPointTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IsBlankBinaryFloatingPointTypesTests = [
        ("testIsBlankCustomMessage", testIsBlankCustomMessage),
        ("testIsBlankDefaultMessage", testIsBlankDefaultMessage),
        ("testIsBlankForNegative", testIsBlankForNegative),
        ("testIsBlankForPositive", testIsBlankForPositive),
        ("testIsBlankForZero", testIsBlankForZero),
        ("testIsNotBlankCustomMessage", testIsNotBlankCustomMessage),
        ("testIsNotBlankDefaultMessage", testIsNotBlankDefaultMessage),
        ("testIsNotBlankForNegative", testIsNotBlankForNegative),
        ("testIsNotBlankForPositive", testIsNotBlankForPositive),
        ("testIsNotBlankForZero", testIsNotBlankForZero),
    ]
}

extension IsBlankBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IsBlankBinaryIntegerTypesTests = [
        ("testIsBlankCustomMessage", testIsBlankCustomMessage),
        ("testIsBlankDefaultMessage", testIsBlankDefaultMessage),
        ("testIsBlankForNegative", testIsBlankForNegative),
        ("testIsBlankForPositive", testIsBlankForPositive),
        ("testIsBlankForZero", testIsBlankForZero),
        ("testIsNotBlankCustomMessage", testIsNotBlankCustomMessage),
        ("testIsNotBlankDefaultMessage", testIsNotBlankDefaultMessage),
        ("testIsNotBlankForNegative", testIsNotBlankForNegative),
        ("testIsNotBlankForPositive", testIsNotBlankForPositive),
        ("testIsNotBlankForZero", testIsNotBlankForZero),
    ]
}

extension IsBlankStringTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IsBlankStringTypesTests = [
        ("testIsBlankCustomMessage", testIsBlankCustomMessage),
        ("testIsBlankDefaultMessage", testIsBlankDefaultMessage),
        ("testIsBlankForEmptyString", testIsBlankForEmptyString),
        ("testIsBlankForNewlineString", testIsBlankForNewlineString),
        ("testIsBlankForNotEmptyString", testIsBlankForNotEmptyString),
        ("testIsBlankForNotNewlineString", testIsBlankForNotNewlineString),
        ("testIsBlankForNotWhitespaceString", testIsBlankForNotWhitespaceString),
        ("testIsBlankForWhitespaceString", testIsBlankForWhitespaceString),
        ("testIsNotBlankCustomMessage", testIsNotBlankCustomMessage),
        ("testIsNotBlankDefaultMessage", testIsNotBlankDefaultMessage),
        ("testIsNotBlankForEmptyString", testIsNotBlankForEmptyString),
        ("testIsNotBlankForNewlineString", testIsNotBlankForNewlineString),
        ("testIsNotBlankForNotEmptyString", testIsNotBlankForNotEmptyString),
        ("testIsNotBlankForNotNewlineString", testIsNotBlankForNotNewlineString),
        ("testIsNotBlankForNotWhitespaceString", testIsNotBlankForNotWhitespaceString),
        ("testIsNotBlankForWhitespaceString", testIsNotBlankForWhitespaceString),
    ]
}

extension IsEmptyArrayTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IsEmptyArrayTypeTests = [
        ("testIsEmptyCustomMessage", testIsEmptyCustomMessage),
        ("testIsEmptyDefaultMessage", testIsEmptyDefaultMessage),
        ("testIsEmptyForEmptyString", testIsEmptyForEmptyString),
        ("testIsEmptyForNotEmptyString", testIsEmptyForNotEmptyString),
        ("testIsNotEmptyCustomMessage", testIsNotEmptyCustomMessage),
        ("testIsNotEmptyDefaultMessage", testIsNotEmptyDefaultMessage),
        ("testIsNotEmptyForEmptyString", testIsNotEmptyForEmptyString),
        ("testIsNotEmptyForNotEmptyString", testIsNotEmptyForNotEmptyString),
    ]
}

extension IsEmptyStringTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IsEmptyStringTypeTests = [
        ("testIsEmptyCustomMessage", testIsEmptyCustomMessage),
        ("testIsEmptyDefaultMessage", testIsEmptyDefaultMessage),
        ("testIsEmptyForEmptyString", testIsEmptyForEmptyString),
        ("testIsEmptyForNotEmptyString", testIsEmptyForNotEmptyString),
        ("testIsEmptyForStringWithSpace", testIsEmptyForStringWithSpace),
        ("testIsNotEmptyCustomMessage", testIsNotEmptyCustomMessage),
        ("testIsNotEmptyDefaultMessage", testIsNotEmptyDefaultMessage),
        ("testIsNotEmptyForEmptyString", testIsNotEmptyForEmptyString),
        ("testIsNotEmptyForNotEmptyString", testIsNotEmptyForNotEmptyString),
        ("testIsNotEmptyForStringWithSpace", testIsNotEmptyForStringWithSpace),
    ]
}

extension IsNilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IsNilTests = [
        ("testIsNilCustomMessage", testIsNilCustomMessage),
        ("testIsNilDefaultMessage", testIsNilDefaultMessage),
        ("testIsNilForNilValue", testIsNilForNilValue),
        ("testIsNilForNotNilValue", testIsNilForNotNilValue),
        ("testIsNotNilCustomMessage", testIsNotNilCustomMessage),
        ("testIsNotNilDefaultMessage", testIsNotNilDefaultMessage),
        ("testIsNotNilForNilValue", testIsNotNilForNilValue),
        ("testIsNotNilForNotNilValue", testIsNotNilForNotNilValue),
    ]
}

extension LessOrEqualThanComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessOrEqualThanComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension LessOrEqualThanDifferentBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessOrEqualThanDifferentBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension LessOrEqualThanSameBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessOrEqualThanSameBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension LessThanComparableTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessThanComparableTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension LessThanDifferentBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessThanDifferentBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension LessThanSameBinaryIntegerTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessThanSameBinaryIntegerTypesTests = [
        ("testCustomMessage", testCustomMessage),
        ("testDefaultMessage", testDefaultMessage),
        ("testEqualCondition", testEqualCondition),
        ("testGreaterCondition", testGreaterCondition),
        ("testLessCondition", testLessCondition),
    ]
}

extension StartsEndsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StartsEndsTests = [
        ("testEndsWithCustomMessage", testEndsWithCustomMessage),
        ("testEndsWithDefaultMessage", testEndsWithDefaultMessage),
        ("testEndsWithEmptyRequiredString", testEndsWithEmptyRequiredString),
        ("testEndsWithStringNotValidCase", testEndsWithStringNotValidCase),
        ("testEndsWithStringValidCase", testEndsWithStringValidCase),
        ("testEndsWithSubstringNotValidCase", testEndsWithSubstringNotValidCase),
        ("testEndsWithSubstringValidCase", testEndsWithSubstringValidCase),
        ("testStartsWithCustomMessage", testStartsWithCustomMessage),
        ("testStartsWithDefaultMessage", testStartsWithDefaultMessage),
        ("testStartsWithEmptyRequiredString", testStartsWithEmptyRequiredString),
        ("testStartsWithStringNotValidCase", testStartsWithStringNotValidCase),
        ("testStartsWithStringValidCase", testStartsWithStringValidCase),
        ("testStartsWithSubstringNotValidCase", testStartsWithSubstringNotValidCase),
        ("testStartsWithSubstringValidCase", testStartsWithSubstringValidCase),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AssertionConcernErrorTests.__allTests__AssertionConcernErrorTests),
        testCase(AssertionConcernGroupSatsifyTests.__allTests__AssertionConcernGroupSatsifyTests),
        testCase(AssertionConcernSatisfyTests.__allTests__AssertionConcernSatisfyTests),
        testCase(AssertionGroupAllTests.__allTests__AssertionGroupAllTests),
        testCase(AssertionGroupAnyOfTests.__allTests__AssertionGroupAnyOfTests),
        testCase(AssertionGroupLazyTests.__allTests__AssertionGroupLazyTests),
        testCase(AssertionNotificationTests.__allTests__AssertionNotificationTests),
        testCase(BetweenBoundsComparableTypesTests.__allTests__BetweenBoundsComparableTypesTests),
        testCase(BetweenBoundsDifferentBinaryIntegerTypesTests.__allTests__BetweenBoundsDifferentBinaryIntegerTypesTests),
        testCase(BetweenBoundsSameBinaryIntegerTypesTests.__allTests__BetweenBoundsSameBinaryIntegerTypesTests),
        testCase(BetweenClosedRangeComparableTypesTests.__allTests__BetweenClosedRangeComparableTypesTests),
        testCase(BetweenMinMaxComparableTypesTests.__allTests__BetweenMinMaxComparableTypesTests),
        testCase(BetweenMinMaxDifferentBinaryIntegerTypesTests.__allTests__BetweenMinMaxDifferentBinaryIntegerTypesTests),
        testCase(BetweenMinMaxSameBinaryIntegerTypesTests.__allTests__BetweenMinMaxSameBinaryIntegerTypesTests),
        testCase(BetweenPartialRangeFromComparableTypesTests.__allTests__BetweenPartialRangeFromComparableTypesTests),
        testCase(BetweenPartialRangeThroughComparableTypesTests.__allTests__BetweenPartialRangeThroughComparableTypesTests),
        testCase(BetweenRangeComparableTypesTests.__allTests__BetweenRangeComparableTypesTests),
        testCase(BoolAssertionsTests.__allTests__BoolAssertionsTests),
        testCase(ClassAssertionsTests.__allTests__ClassAssertionsTests),
        testCase(ContainedInSequenceTypesTests.__allTests__ContainedInSequenceTypesTests),
        testCase(EquatableAssertionsTests.__allTests__EquatableAssertionsTests),
        testCase(GreaterOrEqualComparableTypesTests.__allTests__GreaterOrEqualComparableTypesTests),
        testCase(GreaterOrEqualDifferentBinaryIntegerTypesTests.__allTests__GreaterOrEqualDifferentBinaryIntegerTypesTests),
        testCase(GreaterOrEqualSameBinaryIntegerTypesTests.__allTests__GreaterOrEqualSameBinaryIntegerTypesTests),
        testCase(GreaterThanComparableTypesTests.__allTests__GreaterThanComparableTypesTests),
        testCase(GreaterThanDifferentBinaryIntegerTypesTests.__allTests__GreaterThanDifferentBinaryIntegerTypesTests),
        testCase(GreaterThanSameBinaryIntegerTypesTests.__allTests__GreaterThanSameBinaryIntegerTypesTests),
        testCase(HasSizeCollectionTypesTests.__allTests__HasSizeCollectionTypesTests),
        testCase(IsBlankBinaryFloatingPointTypesTests.__allTests__IsBlankBinaryFloatingPointTypesTests),
        testCase(IsBlankBinaryIntegerTypesTests.__allTests__IsBlankBinaryIntegerTypesTests),
        testCase(IsBlankStringTypesTests.__allTests__IsBlankStringTypesTests),
        testCase(IsEmptyArrayTypeTests.__allTests__IsEmptyArrayTypeTests),
        testCase(IsEmptyStringTypeTests.__allTests__IsEmptyStringTypeTests),
        testCase(IsNilTests.__allTests__IsNilTests),
        testCase(LessOrEqualThanComparableTypesTests.__allTests__LessOrEqualThanComparableTypesTests),
        testCase(LessOrEqualThanDifferentBinaryIntegerTypesTests.__allTests__LessOrEqualThanDifferentBinaryIntegerTypesTests),
        testCase(LessOrEqualThanSameBinaryIntegerTypesTests.__allTests__LessOrEqualThanSameBinaryIntegerTypesTests),
        testCase(LessThanComparableTypesTests.__allTests__LessThanComparableTypesTests),
        testCase(LessThanDifferentBinaryIntegerTypesTests.__allTests__LessThanDifferentBinaryIntegerTypesTests),
        testCase(LessThanSameBinaryIntegerTypesTests.__allTests__LessThanSameBinaryIntegerTypesTests),
        testCase(StartsEndsTests.__allTests__StartsEndsTests),
    ]
}
#endif
